version: '3'
services:
  logseq-sync:
    build: .
    container_name: logseq_sync
    restart: always
    environment:
      - DB_SYNC_PORT=3000
      - DB_SYNC_DATA_DIR=/data
      - COGNITO_ISSUER=${OIDC_ISSUER}
      - COGNITO_CLIENT_ID=${OIDC_CLIENT_ID}
      - DB_SYNC_ALLOW_UNVERIFIED_JWT_CLAIMS=${ALLOW_UNVERIFIED}
    volumes:
      - ${DATA_DIR}:/data
    ports:
      - ${PORT}:3000
